repos:
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-xml
  - id: check-json
  - id: detect-private-key
  - id: check-toml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.8.0
  hooks:
  - id: setup-cfg-fmt
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.15.0
  hooks:
  - id: reorder-python-imports
    args: [--py39-plus, --add-import, 'from __future__ import annotations']
- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.2.0
  hooks:
  - id: add-trailing-comma
